#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run with sudo"
  exit 1
fi

#application files
mkdir /usr/local/etc/digital-ocean
touch /usr/local/etc/digital-ocean/.env
cp digital-ocean-dns-updater.py /usr/local/etc/digital-ocean/
chown -R $SUDO_USER:$SUDO_USER /usr/local/etc/digital-ocean

#log files
mkdir /var/log/digital-ocean
chown -R $SUDO_USER:$SUDO_USER /var/log/digital-ocean

echo "Please enter your api key for digital ocean: "
read -s api_key

echo "API_KEY=$api_key" > /usr/local/etc/digital-ocean/.env
sed "s/USER/$SUDO_USER/g" digital-ocean-dns-updater.service > /etc/systemd/system/digital-ocean-dns-updater.service
cp digital-ocean-dns-updater.timer /etc/systemd/system/
systemctl daemon-reload
systemctl start digital-ocean-dns-updater.timer
systemctl enable digital-ocean-dns-updater.timer
